spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog.yml
server:
  port: 9090